bratislava/paas-mpa

.eslintrc.js
app/examples/styleguide.tsx
components/action-info/AvatarIcon.tsx
components/shared/SegmentBadge.tsx
components/shared/Surface.tsx
components/shared/Typography.tsx
components/showcases/AvatarIconShowcase.tsx
components/showcases/SurfaceShowcase.tsx
components/showcases/TypographyShowcase.tsx
tailwind.config.js

- Typography - all font variants
- Surface - rounded corners, background, padding

implement basic components

---

.eslintrc.js
app/_layout.tsx
app/add-parking-cards/enter-email-addresses.tsx
app/add-parking-cards/verification-sent.tsx
app/onboarding/enter-phone-number.tsx
app/onboarding/enter-verification-code.tsx
app/onboarding/intro.tsx
components/DeveloperMenu.tsx
components/shared/Screen.tsx
components/shared/ScreenContent.tsx
hooks/useTranslation.ts
translations/en.json
translations/sk.json

- hide backbutton title in navigation
- specify text input keyboard type on several screens
- create Screen component
- create `continueProps` in Screen an ScreenContent component
TODOs
- email format verification on FE
- add redirect lint to confirmation screen

init "Add payment cards" screens

---

.eslintrc.js
app/purchase/index.tsx
components/DeveloperMenu.tsx
components/shared/FlexRow.tsx
translations/en.json
translations/sk.json

Only dummy screen with bottom sheet with dynamic height.
resolves #26

#26: init Purchase screen

---

app/examples/bottom-sheet.tsx
app/examples/modal.tsx
app/vehicles/edit-vehicle.tsx
app/vehicles/index.tsx
components/DeveloperMenu.tsx
components/actions/ActionRow.tsx
components/info/AvatarCircle.tsx
components/shared/BottomSheetContent.tsx
components/shared/FlexRow.tsx
components/shared/Modal.tsx
components/vehicles/NoVehicles.tsx
components/vehicles/VehicleRow.tsx
hooks/useVehicles.ts
tailwind.config.js
translations/en.json
translations/sk.json

- implement bottom sheet actions components
- add actions to delete vehicle and to set vehicle as default
- first car in the list is considered default - this may be changed in future
- use FlatList in VehiclesScreen 
- implement modal dialog components - resolves #42 
TODO
- potentially split Modal components into separate files
- add confirm modals before deleting vehicle etc.

feat #34 add actions to manage vehicles

---

app/examples/styleguide.tsx
components/parking-cards/CardContentItem.tsx
components/parking-cards/ParkingCardBase.tsx
components/parking-cards/ParkingCardContent.tsx
components/parking-cards/ResidentCard.tsx
components/parking-cards/VisitorCard.tsx
components/shared/CheckBox.tsx
components/showcases/CheckBoxShowcase.tsx
components/showcases/ParkingCardsShowcase.tsx
package.json
tailwind.config.colors.js
tailwind.config.js
translations/en.json
yarn.lock

#50
Note:
No props implemented yet, I think we can wait for types from BE. 
Bonus card is missing in figma - will discuss with @Zanarova separately.
#55 
TODO: Test on android. @lukybil pls

Feature/#50 parking cards components, #55 CheckBox

---

app/index.tsx
app/purchase/choose-payment-method.tsx
app/purchase/choose-vehicle.tsx
app/purchase/custom-time.tsx
app/purchase/index.tsx
app/vehicles/add-vehicle.tsx
components/controls/date-time/DateTimePicker.tsx
components/controls/date-time/TimeSelector.tsx
components/map/MapScreen.tsx
components/shared/BottomSheetContent.tsx
components/shared/ScreenContent.tsx
components/shared/ScreenView.tsx
utils/formatDuration.ts
utils/formatMinutes.tsx
utils/types.ts

- add Valid unit value to TimeSelector
- fix lost params when visiting payment methods modal
- rename `time` to `duration`
- add fixed payment button to the bottom of the purchase screen
- other minor improvements and cleanup

improve and fix purchase screen components and flow

---

.eslintrc.js
components/inputs/Autocomplete.tsx
components/map/Map.tsx
components/map/MapAutocomplete.tsx
components/map/MapScreen.tsx
components/map/MapZoneBottomSheet.tsx
modules/map/types.ts
modules/map/utils/forwardGeocode.ts
modules/map/utils/layer-styles/markers.ts

- added generic `Autocomplete`
- added geocoding search to BottomSheet

#70 Full text search

---

.eslintrc.js
app/parking-cards/enter-paas-account.tsx
app/parking-cards/index.tsx
app/purchase/index.tsx
components/controls/notifications/NotificationSettings.tsx
components/shared/Button.tsx
modules/backend/openapi-generated/api.ts
package.json
translations/en.json
yarn.lock

- upgrade React Query to new v5.0.0
- fix `Button`'s disabled state on loading
- add some translations
- make some eslint rules only warn - these may potentially be disabled completely, because they are triggered by other libraries such as react query, which we do not control 
- sent request with new email to verify (token should be returned for now) - TODO mailgun does not work now
- implement optimistic update for Notification settings  - cloces #103 
TODO
- error handling - show snackbar?
- typing for optimistic update
- etc..

feat: #106 request parking cards

---

app/(purchase-and-payment)/purchase/index.tsx
app/_layout.tsx
app/parking-cards/[email].tsx
app/parking-cards/index.tsx
app/tickets/index.tsx
components/controls/notifications/NotificationSettings.tsx
components/controls/payment-methods/VisitorCardsField.tsx
components/map/MapZoneBottomSheetAttachment.tsx
components/screen-layout/Snackbar/Snackbar.tsx
components/special/AxiosResponseInterceptors.tsx
components/special/OmnipresentComponent.tsx
hooks/useQueryWithFocusRefetch.ts
modules/arcgis/hooks/useStaticArcgisData.ts
modules/backend/hooks/useAxiosResponseInterceptors.ts
modules/map/hooks/useProcessedArcgisData.ts

- refetch on app refocus
- set `gcTime` (garbage colletion time, former `cacheTime`) of queries to 60 minutes from the default 5 minutes 
- resolved comments for previous PRs

#101: Refetch on refocus

---

app/(purchase-and-payment)/purchase/index.tsx
app/announcements/index.tsx
app/index.tsx
components/controls/payment-methods/BonusCardMethod.tsx
components/controls/payment-methods/VisitorCardMethod.tsx
components/tickets/PurchaseBottomSheet.tsx
components/tickets/TicketCard.tsx
modules/backend/constants/queryOptions.ts
modules/backend/hooks/usePrefetchOnAppStart.tsx
modules/backend/openapi-generated/api.ts
modules/map/utils/normalizeZone.ts

TODO
- show BPK remaining credit and validUntil date

feat: show cards restrictions info, update api

---

app/zone-details/index.tsx
components/controls/ParkingZoneField.tsx
components/map/MapZoneBottomSheet.tsx
modules/map/types.ts
modules/map/utils/normalizeZone.ts

- it just makes sense to work with `urdId` as with string

normalize udrId as string

---

components/inputs/Autocomplete.tsx
components/inputs/TextInput.tsx
components/map/Map.tsx
components/map/MapAutocomplete.tsx
components/map/MapScreen.tsx
components/map/MapZoneBottomSheet.tsx
modules/map/hooks/useProcessedArcgisData.ts
modules/map/types.ts
modules/map/utils/findPolygonCenter.ts
translations/en.json
translations/sk.json

- search for zones in the MapAutocomplete by name or udr id
- only execute process data once, this seems actually to be the **largest bottleneck for the whole application**, not the map itself

#159: Search zones

---

app/(auth)/confirm-sign-in.tsx
app/(auth)/sign-in.tsx
app/index.tsx
app/payment-options/index.tsx
components/DeveloperMenu.tsx
components/controls/payment-methods/PaymentOptionsField.tsx
components/navigation/MainMenu/MainMenuBottomSheet.tsx
translations/en.json
translations/sk.json

- add missing translations
- move bottom sheet into ScreenView to see if it helps to render ActionRows inside on android
- redirect to map from sign-in and confirm-sign=in screens if user is logged in
- hide apple pay from options on android

minor visual and translations fixes

---

app/(auth)/sign-in.tsx
components/inputs/TextInput.tsx
components/navigation/MainMenu/MainMenuBottomSheet.tsx

- remove spaces in phone number during sign in - closes #195 
- add keyboard Done button on sign in page
- tmp fix TextInput's text line height - closes #191 
- fix translation in main menu
Done button on ios:

minor visual fixes

---

app/(app)/parking-cards/verification/index.tsx
app/(app)/parking-cards/verification/verification-sent.tsx
app/(app)/vehicles/add-vehicle.tsx
app/(auth)/confirm-sign-in.tsx
app/(auth)/sign-in.tsx
components/shared/DissmissKeyboard.tsx

- Dismissing keyboard on click outside the input
- KeyboardAvoidingView component to email verification

Bugfix keyboard avoiding view

---

app/(app)/about/index.tsx
app/(app)/index.tsx
components/navigation/MainMenu/MainMenuBottomSheet.tsx

- hide dev and unused parts from menu
Just as quick solution to be ready for app review.

hide DEV and unused menus

---

.eslintrc.js
app/(app)/parking-cards/[email].tsx
app/(app)/settings/index.tsx
app/(app)/tickets/index.tsx
components/controls/date-time/CustomDateTimePicker.tsx
components/controls/date-time/lib/ScrollViewPicker.tsx
components/map/MapMarkers.tsx
components/map/MapZoneBottomSheet.tsx
components/screen-layout/BottomSheet/BottomSheetHandleWithShadow.tsx
components/screen-layout/Snackbar/Snackbar.tsx
components/showcases/ButtonShowcase.tsx

feat: #264 disable eslint rule react-native/no-inline-styles

---

app/(auth)/confirm-sign-in.tsx
app/(auth)/sign-in.tsx
hooks/useSignInOrSignUp.ts
translations/en.json
translations/sk.json

- displayed phone validation error when signing in (closes #249)
- added loading when signing in
- moved permission route change from confirm-sign-in to hook (it was called twice and that caused the map page error) (closes #221)

invalid phone number errors and map page warning

---

.env
app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
app/(app)/menu.tsx
app/(app)/parking-cards/verification/verification-sent.tsx
app/(app)/tickets/index.tsx
app/onboarding/index.tsx
components/controls/date-time/TimeSelector.tsx
eas.json
environment.ts
modules/backend/constants/queryOptions.ts
modules/backend/openapi-generated/api.ts

closes #311 
- differentiate staging from production and development 
- fix in filtering
- correct time value in prolongation

Bugfix tickets filtering

---

app/(app)/menu.tsx
app/(app)/parking-cards/verification/verification-sent.tsx
components/tickets/PurchaseBottomContent.tsx

Add padding for screens with no safe area insets.

fix Pay button padding

---

components/map/Map.tsx
components/map/MapAutocomplete.tsx
components/map/MapPointBottomSheet.tsx
modules/arcgis/hooks/useArcgisData.ts
modules/arcgis/hooks/useStaticArcgisData.ts
modules/arcgis/types.ts
modules/map/hooks/useCameraChangeHandler.ts
modules/map/types.ts
modules/map/utils/normalizePoint.ts
modules/map/utils/processData.ts
package.json
translations/en.json
translations/sk.json
yarn.lock

- #295 reduce rectangle size, introduce screen scale, must be tested on iOS
- #283 disable 3D map view
- #259 change `MapPointBottomSheet` title to the kind of the point
- #260 `MapPointBottomSheet` change the shown attributes
- #293 remove redundant address text

Sprint 15 map bug fixes

---

app/(app)/parking-cards/verification/index.tsx
translations/en.json
translations/sk.json
utils/errorService.ts
utils/isValidEmail.ts

- parking card validation (closes #308)

parking card errors

---

app/(app)/(purchase-and-payment)/purchase/index.tsx
app/(app)/parking-cards/[email].tsx
app/(app)/parking-cards/index.tsx
app/(app)/parking-cards/verification/verification-result.tsx
app/(app)/tickets/index.tsx
components/controls/payment-methods/UsedBonusCard.tsx
components/controls/payment-methods/VisitorCardsField.tsx
components/parking-cards/ParkingCard.tsx
components/parking-cards/cards/BonusCard.tsx
components/showcases/ParkingCardsShowcase.tsx
components/tickets/TicketCard.tsx
hooks/useFirstPurchaseStorage.ts
translations/en.json
translations/sk.json

- add ticketReceipt mutation (closes #194)
- remove active tab text from parking cards (closes #314)
- modal to ask for parking cards at first purchase (closes #316)
- no parking cards button to add parking card (closes #317)
- bonus card remaining credit (closes #330)

Feature receipt download

---

app/(app)/parking-cards/verification/verification-result.tsx
components/controls/notifications/NotificationSettings.tsx
modules/backend/constants/queryOptions.ts

- fixed going back to emails page from validation success page (closes #337)
- optimistic updates on notificationSettings (closes #103)

navigate back to correct route from validation result page

---

app/(app)/zone-details.tsx
components/controls/ParkingZoneField.tsx
components/map/Map.tsx
components/map/MapZoneBottomSheetPanel.tsx
package.json
translations/en.json
translations/sk.json
utils/getPriceFromZone.ts
yarn.lock

- display weekend and holidays price

#345: Weekend ticket prices

---

app/permissions.tsx
hooks/useSignInOrSignUp.ts
modules/backend/constants/queryOptions.ts
modules/map/hooks/useLocationPermission.ts
modules/map/hooks/useNotificationPermission.ts

- added automatic check to be able not to register someones token twice (closes #378)
- added permissions check to skip permission screens (closes #380)

notification token exists check and permision screens checks

---

app/onboarding.tsx
hooks/useClearHistory.ts
hooks/useSignInOrSignUp.ts
modules/map/hooks/useLocation.ts
modules/map/hooks/useNotificationPermission.ts

adding focus effect to onboarding screen instead of triggering it in outer scope
it was triggered in background
- checked notification flow (closes #379)
- fixed location permissions warning (closes #305)

fix of double login bug

---

app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
app/(app)/feedback/index.tsx
app/(app)/parking-cards/verification/index.tsx
app/(app)/vehicles/add-vehicle.tsx
app/(auth)/confirm-sign-in.tsx
app/onboarding.tsx
components/controls/notifications/NotificationControl.tsx
components/controls/notifications/SwitchControl.tsx
components/inputs/CodeInput.tsx
components/inputs/TextInput.tsx
components/list-rows/SelectRow.tsx
components/map/MapLocationBottomSheet.tsx
components/map/MapZoneBottomSheet.tsx
components/navigation/MarketingTabBar.tsx
components/shared/AccessibilityField.tsx
components/shared/CheckBox.tsx
components/shared/Field.tsx
components/shared/PressableStyled.tsx
components/showcases/FieldShowcase.tsx
components/showcases/SwitchShowcase.tsx
translations/en.json
translations/sk.json

improved accessibility in multiple places 
hopefully closes #397, closes #398, closes #399 
needs to be checked with google play console

Improvement accessibility

---

app/(app)/feedback/index.tsx
app/(app)/search.tsx
components/map/Map.tsx
components/map/MapZoneBottomSheet.tsx
components/shared/AccessibilityField.tsx
components/shared/DissmissKeyboard.tsx
translations/en.json
translations/sk.json

changes found in voiceover testing like: 
- DismissKeyboard component accessibility turned to false so it wont show in reader
- old Keyboard.dismiss removal or swap with DismissKeyboard
- AccessibilityField correcting label 
- translation for a place where no Field component is used.
linked issue - #366

Accessibility changes based on iOS VoiceOver testing

---

components/screen-layout/StackScreenWithHeader.tsx

- added close button to screens with modal presentation type (closes #326)
NEEDS TESTING ON ANDROID DEVICE!

back button with presentation modal

---

app/(app)/parking-cards/verification/verification-sent.tsx

fix: verification code input fix

---

app/(app)/(purchase-and-payment)/purchase/index.tsx
components/controls/vehicles/VehicleFieldControl.tsx
components/tickets/PurchaseBottomContent.tsx
translations/en.json
translations/sk.json

- added hasLicencePlateError state that changes to true when user clicks on pay button and no licence plate is provided 
- it resolves when licence plate is filled 
closes #422

#422: added error when no licence plate provided

---

app/_layout.tsx
components/info/AvatarCircleNetworkOff.tsx
components/screen-layout/Modal/ModalContainer.tsx
components/showcases/AvatarShowcase.tsx
components/special/AxiosConnection.tsx
components/special/NetworkConnection.tsx
components/special/OmnipresentComponent.tsx
components/special/StoreVersionControl.tsx
modules/backend/constants/queryOptions.ts
modules/backend/hooks/useAxiosResponseInterceptors.ts
modules/backend/openapi-generated/api.ts
package.json
translations/en.json
translations/sk.json
yarn.lock

- added modals to check server and network connection (closes #434)

network and server connection components

---

app/(app)/(purchase-and-payment)/purchase/index.tsx
components/controls/date-time/DateTimePicker.tsx
components/controls/date-time/TimeSelector.tsx
components/tickets/PurchaseBottomContent.tsx
translations/en.json
translations/sk.json
utils/formatTime.ts

- warning when parking end differs with requested parking end (closes #443)
- translations of time picker (closes #418)
- added initialValue to datepicker to choose based on current parking end not present time

changed parking end warning and translations

---

app/(auth)/sign-in/index.tsx

- when prefilling number with country code the country code will not be filled twice (closes #446)
- when prefilling number with different country code the country will change

Better ux when filling the phone number

---

components/controls/date-time/DateTimePicker.tsx
components/controls/date-time/TimeSelector.tsx

- changed minimum time in prolongation to not be able to go to negative values ,
- prolongation calculated from now when using custom time, but it should be from last ticket end (closes #452)
- code improvements to have values in constant

fix: custom time

---

app/(app)/menu.tsx
app/(app)/parking-cards/[email].tsx
app/(app)/parking-cards/verification/index.tsx
app/(app)/payment-options.tsx
app/(app)/settings/index.tsx
app/(app)/tickets/index.tsx
app/(app)/vehicles/index.tsx
app/(app)/zone-details.tsx
app/_layout.tsx
components/inputs/CodeInput.tsx
components/inputs/TextInput.tsx
components/map/MapZoneBottomSheet.tsx
components/map/MapZoneBottomSheetPanel.tsx
components/parking-cards/EmailsBottomSheet.tsx
components/parking-cards/ParkingCard.tsx
components/parking-cards/cards/VisitorCard.tsx
components/screen-layout/BottomSheet/BottomSheetContent.tsx
components/shared/Icon.tsx
components/shared/Typography.tsx
components/showcases/ParkingCardsShowcase.tsx
translations/en.json
translations/sk.json

- maximum accessibility text size (closes #459),
- lowercase email address (closes #460 ),
- dynamic bottom sheet height,
- bottom sheets above headers,
- not necessary filter button when no history tickets are available,
- visitor card id removal (not necessary for user)

issues with testing

---

app/(app)/_layout.tsx
app/(app)/parking-cards/index.tsx
app/(app)/parking-cards/verification/index.tsx
modules/arcgis/hooks/useStaticArcgisData.ts
translations/en.json
translations/sk.json

added links to paas website based on design (closes #449)

feat: link to paas website

---

app/(app)/feedback/index.tsx

added version and build number to feedback message

---

app/(app)/menu.tsx
components/tickets/TicketCard.tsx
modules/arcgis/hooks/useStaticArcgisData.ts

- refetch arcgis data at 12:05AM each day (closes #468)
- hide announcements menu icon (closes #473)
- active ticket download ticket pdf removal (closes #471)

Bugfix download ticket receipt

---

app/(app)/parking-cards/verification/verification-result.tsx
app/(app)/parking-cards/verification/verification-sent.tsx
app/onboarding.tsx
i18n.config.js
translations/en.json
translations/sk.json
yarn.lock

- added texts based on Patrik's suggestions to inform user about added licence plates,
- added translations with plural forms based on count variable (each locale has different syntax for this practice)

improvement: texts about added LicencePlates

---

components/tickets/TicketCard.tsx
translations/en.json
translations/sk.json

- update texts
- small fix in termination condition when shortening the ticket

Improvement text changes

---

app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
app/(app)/(purchase-and-payment)/purchase/index.tsx
app/(app)/(purchase-and-payment)/ticket-purchase.tsx

- showing card fix,
- back button in payment fix

fix: remember card field and back button

---

app/(app)/feedback/index.tsx
modules/backend/openapi-generated/api.ts

- update regarding to changes in api

Fix FeedbackType type

---

app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
app/(app)/dev/index.tsx
app/(app)/menu.tsx
app/(app)/tickets/filters/index.tsx
app/(app)/tickets/filters/timeframes.tsx
app/(app)/tickets/filters/vehicles.tsx
app/(app)/tickets/index.tsx
app/onboarding.tsx
app/permissions.tsx
components/map/MapZoneBottomSheetAttachment.tsx
components/parking-cards/EmailsBottomSheet.tsx
components/screen-layout/InfoSlide.tsx
components/tickets/TicketCard.tsx
components/tickets/TicketsHistoryBottomSheet.tsx
hooks/useQueryInvalidateOnTicketExpire.ts
modules/backend/constants/queryOptions.ts
translations/en.json
translations/sk.json

- Minor cleanup and fixes
- Simplify components on Tickets screen
- Make possible to refresh empty tickets lists by using `ListEmptyComponent`
- Add `filters.timeframe` to `queryKey`
- Fix minor visual issues

#503 Fix Tickets caching

---

app/(app)/dev/examples/user.tsx
app/permissions.tsx
components/controls/notifications/NotificationSettings.tsx
hooks/useSignInOrSignUp.ts
modules/backend/axios-instance.ts
modules/map/hooks/useNotificationPermission.ts
modules/map/hooks/useRegisterDevice.ts

The aim of this rewrite is to keep the same functionality and behaviour, but write it in cleaner form (divide responsibilities into separate functions and hooks). Any functionality updates should be done in further PRs.

Rewrite notification permission code to simpler functions

---

app/(app)/zone-details.tsx
components/controls/ParkingZoneField.tsx
components/controls/vehicles/VehicleRow.tsx
modules/arcgis/hooks/useStaticArcgisData.ts

#554, #532: Fix overflown long zone name and vehicle names

---

app/(app)/parking-cards/index.tsx
app/(app)/parking-cards/verification/verification-sent.tsx
app/(auth)/confirm-sign-in.tsx
app/_layout.tsx
components/parking-cards/EmailsBottomSheet.tsx
translations/en.json
translations/sk.json

See commits
- resolves bratislava/paas-mpa-private#2
- please see and test the use-cases mentioned in the issue
- resolves #565 #566 
(I'm also testing how we can reference private issues from other repo, therefore #2, but I see that in commits, it obviously links to PRs/issues in this repo)

#2, #556, #566: Fix add/delete parking cards, safe area padding, field label

---

app/(app)/parking-cards/[email].tsx

#374 Adjust parking cards list for better UX

---

eas.json

Note: We are testing more ios settings in eas.json.

Add production-testing profile

---

app/(app)/(purchase-and-payment)/purchase/index.tsx
modules/backend/axios-instance.ts

Fetch only if screen is focused - TESTED.
Note: When custom date is open, it does not prevent refetching, because it is not a page, just some modal.

#575 Add interval to request price every minute

---

app/(auth)/sign-in/index.tsx

#591 Remove leading zero in login value

---

modules/map/hooks/useNotificationPermission.ts

- closes bratislava/paas-mpa-private#5

Private/#5: Fix notification settings after permissions are allowed

---

components/map/MapZoneBottomSheet.tsx
components/map/MapZoneBottomSheetPanel.tsx
translations/en.json
translations/sk.json

#557 Disallow to open purchase screen from planned zones

---

app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
app/(app)/vehicles/add-vehicle.tsx

#536 Limit licence plate length to 15 characters

---

components/purchase/PaymentStatus/ErrorContent.tsx
components/purchase/PaymentStatus/PaymentStatusContent.tsx

These messages were never meant to be shown on FE.
- closes #547

#547 Hide error messages from payment gateway in FE

---

app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
app/(app)/(purchase-and-payment)/purchase/index.tsx
utils/createPriceRequestBody.ts
utils/getPaygateLanguageFromLocale.ts

#513 Add language to payment request to open paygate in user's locale

---

app/permissions.tsx
components/controls/notifications/NotificationSettings.tsx
hooks/useSignInOrSignUp.ts
modules/map/hooks/useNotificationPermission.ts
utils/requestNotificationPermissionAsync.android.ts
utils/types.ts

- minor renaming in first commit
- add missing request for notification permission on Android

#594 Request notification permission on Android

---

app.config.js

Change the purpose string to fix Apple's release rejection.

purpose string change

---

app/(app)/feedback/index.tsx
utils/isValidEmail.ts

Changed regex to this `/.*@.*\..*/` and it means this:
- `.*` zero or more of any characters,
- `@` matches the "@" symbol,
- `.*` zero or more of any characters,
- `\.` matches escaped "." character,
- `.*` zero or more of any characters,

Less strict email check

---

app/(app)/parking-cards/verification/verification-sent.tsx

invalidate vehicles query after adding parking cards email successfully (closes #621)

Invalidate vehicles query after adding parking cards

---

app/(auth)/confirm-sign-in.tsx
translations/en.json
translations/sk.json

#633 Show phone number in confirm sign-in screen text

---

app/(app)/feedback/index.tsx
app/(auth)/sign-in/index.tsx
components/inputs/TextInput.tsx
components/showcases/TextInputShowcase.tsx

Refactor of input component so it allows user to use it natively as user should be able to :) (closes #535) 
!needs deeper testing after merging this PR!

#535 Refactor TextField component to accept native events

---

app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
app/(app)/vehicles/add-vehicle.tsx
state/VehiclesStoreProvider/VehiclesStoreProvider.tsx
utils/createPriceRequestBody.ts

Use sanitized version of licence plate in one time licence plate

---

components/parking-cards/ParkingCard.tsx
modules/backend/openapi-generated/api.ts

- run generate clients and
- add social type from API enum to ParkingCard component

#370 add social into ParkingCard component

---

app.config.js
eas.json
package.json

change them to the ones we agreed on

Change name of profiles in eas.json

---

app/(app)/feedback/index.tsx
components/controls/feedback/FeedbackTypeSwitch.tsx
package.json
yarn.lock

includes new react-hook-form library that handles all the blurs and submission of form

#622 Refactor feedback screen

---

hooks/useLiveActivities.ts
modules/live-activity-module/ios/Attributes.swift
modules/live-activity-module/ios/LiveActivityControlModule.swift
modules/live-activity-module/src/LiveActivityControlModule.ts
targets/live-activity/Attributes.swift
targets/live-activity/LiveActivity.swift

send app locale to live activity

#687 localization in live activities

---

app/(app)/feedback/index.tsx
components/controls/feedback/FeedbackTypeSwitch.tsx
modules/backend/openapi-generated/api.ts

- usage of different property in BE call (feedbackType instead of type)

#273 Adjust feedback based on changes in BE

---

app/(app)/about/index.tsx
app/(app)/menu.tsx
translations/en.json
translations/sk.json

#714 add links to external service and faq page

---

app/(app)/filters.tsx
assets/map/images/index.ts
components/map/MapMarkers.tsx
components/map/MapPointBottomSheet.tsx
modules/arcgis/aliasedTypes.ts
modules/arcgis/types.ts
modules/map/constants.ts
translations/en.json
translations/sk.json
utils/isWinterHolidayPeriod.ts

remove TODO flag because we can keep the code the whole year

#719 add isWinterHolidayPeriod check to map feature

---

app.config.js
app/(auth)/sign-in/index.tsx
components/inputs/Captcha.tsx
eas.json
hooks/useSignInOrSignUp.ts
modules/cognito/utils.ts
package.json

- change captcha to managed,
- remove retry of captcha and don't send user to cognito if captcha fails,
- add prefix to signIn function so we can work with this in lambda,
- change the function parameters to one object of values,
- version change to 1.7.0,
- change env for staging and dev turnstile site key

#732 Change captcha from invisible to managed 

---

app.config.js
components/inputs/Captcha.tsx
hooks/useSignInOrSignUp.ts
package.json
translations/en.json
translations/sk.json

- add meta tag to captcha so it gets size of device,
- change captcha size to `flexible`
- remove custom error message from snackbar and show only generic ones

#732 Fix captcha size

---

.maestro/add-parking-cards.yaml
.maestro/prolongate.yaml
app/(app)/parking-cards/verification/index.tsx
app/(app)/parking-cards/verification/verification-result.tsx
app/(app)/parking-cards/verification/verification-sent.tsx

- remove unnecessary conditions from tests (now that BE is fixed the paygate is in language of user),
- remove wrong condition from parking cards... we don't need the second pard (it was wrong),
- show different result screen based on number of cards added

Fix parking cards
