bratislava/paas-mpa

- .prettierrc.js
- app/index.tsx
- app/parking-cards/enter-paas-account.tsx
- app/parking-cards/index.tsx
- app/parking-cards/verification-sent.tsx
- app/payment-methods/index.tsx
- app/settings/index.tsx
- app/tickets/index.tsx
- app/vehicles/index.tsx
- components/DeveloperMenu.tsx
- components/actions/ActionRow.tsx
- components/shared/BottomSheetContent.tsx
- package.json
- translations/en.json
- translations/sk.json
- yarn.lock
Implement simple main menu in detached bottom sheet. This solution works with one Stack navigator.
I tried Drawer, but it needs more setup and proper combination with Stack navigation, so I think this is fine for now. Also google maps have similar "modal" when taping on avatar icon.
TODOs if we keep this menu:
- X button instead of handle
- solve header style / X button / transparent bg...
> [#51] implement main menu in detached bottom sheet

- app/index.tsx
- components/actions/ActionRow.tsx
- components/controls/payment-methods/PaymentGate.tsx
- components/controls/vehicles/VehicleFieldControl.tsx
- components/controls/vehicles/VehicleRow.tsx
- components/shared/Button.tsx
- components/shared/Icon.tsx
- components/shared/IconButton.tsx
- components/shared/Modal.tsx
- components/showcases/ButtonShowcase.tsx
- components/showcases/ListRowsShowcase.tsx
- implement `IconButton` with required `accessibilityLabel`
- add `forwardRef` to IconButton and to ActionRow - this may need revisit how we treat Pressable components
- resolves #60
> [#60] implement IconButton and add forwardRef for other components

- app/_layout.tsx
- app/examples/styleguide.tsx
- app/purchase/custom-time.tsx
- app/purchase/index.tsx
- components/controls/TimeSelector.tsx
- components/controls/vehicles/VehicleField.tsx
- components/shared/Chip.tsx
- components/showcases/TimeSelectorShowcase.tsx
- hooks/useTimeSelector.tsx
- tailwind.config.js
- translations/en.json
- translations/sk.json
- utils/formatMinutes.tsx
TimeSelector with pre-defined time chips.
TODO:
- set custom time when entered on "Custom time" screen
- highlight "custom" chip when no other ships match the time value
- compute "valid until" information
- implement "Custom time" screen with datetime picker - now it has only simple text input (that does not pass the value anywhere).
Notes:
- Text seemed to be smaller in general than desired - units had to be changes to `px` instead of `rem`.
- Chips with label formatted by `formatMinutes` function are collapsed (with no label) when in simple `View`. In `ScrollView` it works. - needs investigation
> [#27] implement TimeSelector

- app/_layout.tsx
- app/examples/bottom-sheet.tsx
- components/map/Map.tsx
- components/map/MapMarkers.tsx
- components/map/MapPointBottomSheet.tsx
- components/map/MapScreen.tsx
- components/map/MapZoneBottomSheet.tsx
- components/map/NavigateBottomSheetFooter.tsx
- components/shared/Field.tsx
- components/shared/Typography.tsx
- modules/map/constants.ts
- modules/map/types.ts
- modules/map/utils/layer-styles/markers.ts
- modules/map/utils/normalizePoint.ts
- modules/map/utils/processData.ts
- package.json
- translations/en.json
- translations/sk.json
- added point detail BottomSheet
- points for a discussion:
- **how to handle point clustering, should all types of points be clustered together?** This is the way it is for the map on the PaaS website, or should the points be clustered separately? This would show the correct icon for clusters, it is the current behavior
- the data format for the point types is almost completely different for all of them, the variable names are in Slovak (why? 😧) some of them do not have an address, some of them do not have a navigation URL, some do not have a name, **what data do we want to show, since the design handles only one from the 7 cases?**
- also, the format of the data is very weird to say the least, e.g. `"N/A"` values instead of a `null`, opening hours are not formatted but are a single line …
> Point detail BottomSheet

- app/auth.tsx
- app/confirm-signin.tsx
- app/confirm-signup.tsx
- app/parking-cards/[email].tsx
- app/parking-cards/index.tsx
- app/parking-cards/verification/index.tsx
- app/parking-cards/verification/verification-result.tsx
- app/parking-cards/verification/verification-sent.tsx
- components/inputs/Autocomplete.tsx
- components/parking-cards/EmailsBottomSheet.tsx
- translations/en.json
- translations/sk.json
- implement `/parking-cards/verification/verification-result` page, that handle redirects from BE to show email verification status
- refetch verified emails when added or deleted
- reorganize verification screens
- add some TextInput props to improve UX
- add empty state screens
- EmptyStateScreen still need some updates (it's not always whole screen, reflect screen title and content title...)
TODO
- deduplicate mutation code for sending verification email
> feat/#144: implement verification result screens

- app/auth.tsx
- app/confirm-signin.tsx
- app/confirm-signup.tsx
- hooks/useSignInOrSignUp.ts
- MFA forces us to enter second code after first login (first code is registration verification, second code is authentication verification)
- this PR just provides the ability to enter this second code without error
Note:
The aim is to make it work without two verification codes, in future PR.
> quickfix registration process by two confirm screens

- app/announcements/index.tsx
- app/examples/empty-state-example.tsx
- app/index.tsx
- app/parking-cards/[email].tsx
- app/parking-cards/index.tsx
- app/tickets/index.tsx
- app/zone-details/index.tsx
- components/map/MapZoneBottomSheet.tsx
- components/screen-layout/EmptyStateScreen.tsx
- components/screen-layout/ScreenView.tsx
- modules/backend/openapi-generated/api.ts
- translations/en.json
- translations/sk.json
- conditionally render `<Stack.Screen>` only if `title` is provided - this allows us to use `EmptyStateScreen` inside `ScreenView` without overriding title
- few minor changes in `EmptyStateScreen`
- add some translations for Tickets screen
- update api
> Fix: quickfix EmptyStateScreen + minor updates

- app/_layout.tsx
- components/info/AvatarSquare.tsx
See  https://github.com/marklawlor/nativewind/issues/308 - "Base scaling has changed" and "rem Units" sections
Predefined and arbitrary values should match now (`h-10` = `h-[40px]`)
We should investigate more, how to do sizing in nativewind, why rem is 14 by default and how to use it together with pixels (some components use pixels instead of rems, e.g. `size` in `<Icon>`)
There is also Nativewind v4 comming soon.
> Fix: quickfix sizes by setting rem to 16

- app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
- components/controls/vehicles/NoVehicles.tsx
- components/map/MapZoneBottomSheet.tsx
- components/parking-cards/EmailsBottomSheet.tsx
- components/screen-layout/BottomSheet/BottomSheetContent.tsx
- components/screen-layout/ScreenView.tsx
Fixing height by adding flex: 0 and minheight as mentioned here: https://github.com/gorhom/react-native-bottom-sheet/issues/1573
Other changes are just minor fixes and cleanups.
MapZoneBottomSheet still needs better height setup.
> try to improve height of bottom sheets

- app.config.js
Only simple versioning is supported:
"CFBundleShortVersionString (version field in app.json/app.config.js) must be a period-separated list of three non-negative integers. Current value: 1.0.2-alpha.0"
> change app version to 1.0.3

- app/(app)/(purchase-and-payment)/purchase/index.tsx
- app/(app)/(purchase-and-payment)/purchase/payment.tsx
- components/controls/date-time/TimeSelector.tsx
- components/purchase/PurchaseErrorPanel.tsx
- components/purchase/PurchaseSummaryRow.tsx
- components/screen-layout/BottomSheet/BottomSheetHandleWithShadow.tsx
- components/tickets/PurchaseBottomSheet.tsx
- translations/en.json
- translations/sk.json
- utils/errorPricingApi.ts
- utils/isDefined.ts
- redirect directly to confirmation screen on purchases that are zero price (NPK, BPK)
- add translations keys for missing errors - TODO translations
- re-organize components in purchase screen
- move Pay button to main purchase screen
- keep only additional details in PurchaseBottomSheet
- create `PurchaseSummaryRow` and `PurchaseErrorPanel` to separate components
- check pricing api error to display `PurchaseErrorPanel` only for code 422 and `errorName` that matcher pricing api error
- fix duration from custom time
> fix #117: Skip payment gate when not needed

- app/onboarding/index.tsx
Fixes #196 
- hidden text fix with flex-shrink on image if needed
- fix of no being able to fully click on bottom `next` button
> onboarding text fix and onboarding bottom button fix

- app.config.js
- app/(app)/settings/index.tsx
- app/(auth)/confirm-sign-in.tsx
- app/(auth)/sign-in.tsx
- hooks/useSignInOrSignUp.ts
- modules/cognito/amplify.ts
- modules/cognito/hooks/useSignOut.ts
- modules/cognito/utils.ts
- modules/map/hooks/useNotificationPermission.ts
- package.json
- state/AuthStoreProvider/AuthStoreProvider.tsx
- state/AuthStoreProvider/useUserMMKVInstance.ts
- translations/en.json
- translations/sk.json
- utils/errorCognitoAuth.ts
- yarn.lock
Closes #265 
- upgrade `aws-aplify` to v6
- update amplify setup to match new version
- implement custom `authFlowType` for static number for review process
- add comments and links to docs
In addition:
- replace `+` by placeholder "+421" in login screen input
- fix stuck flow on Notification permissions screen on ios simulator
TODOs:
- handle already signed in user properly
- handle wrong phone number format properly
> [#265] upgrade aws-amplify and implement static login

- hooks/useSignInOrSignUp.ts
After change in user pool settings, we now get and check `UserNotFoundException` as expected.
- fixes #270
> check only non-existing users to continue to sing-up

- app/(app)/settings/language.tsx
- app/(auth)/confirm-sign-in.tsx
- components/controls/LangugageSelectField.tsx
- utils/changeUserLanguageToDevice.ts
adding language also to MMKV storage to keep the last language stored in case of logging out (closes #376)
there was a bug that if I log out, kill app and then open it again the device language will be used 
now the priority order is: API language -  mmkv language - device language.
if there is difference in api and mmkv language the api will rewrite mmkv language
> keep last selected language when logging out

- app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
- app/(app)/(purchase-and-payment)/purchase/index.tsx
- utils/createPriceRequestBody.ts
- added debounce for the duration in price calculation (both prolongation and first purchase) (closes #357)
the first purchase has to have a separate function to have the freshest parkingStart when clicking the pay button
prolongation doesn't have this usecase because using parkingStart from an old ticket and not the current time
> debouncing duration

- modules/arcgis/hooks/useStaticArcgisData.ts
caching data from gis (closes #350)
- it's done by fetching only headers first and checking etag value which will be compared (etag is version of the file) and if so the new data are fetched.
> caching gis data

- components/controls/date-time/DateTimePicker.tsx
- components/map/MapLocationBottomSheet.tsx
- components/map/MapScreen.tsx
- components/map/MapZoneBottomSheet.tsx
- components/map/MapZoneBottomSheetAttachment.tsx
- components/screen-layout/StackScreenWithHeader.tsx
- modules/map/hooks/useLocationPermission.ts
- modules/map/hooks/useNotificationPermission.ts
- changed requesting location functions to ask only once when it's not determined or when denied and `canAskAgain` is true (closes #416),
- gps ask twice fix by removing it from MapZoneBottomSheetAttachment component (closes #403),
- removed unnecessary ref,
- one portal instead of three,
- simulator permissions screen navigated from navigation to homescreen, now it navigates to location permissions screen,
- changed datepicker on android (closes #417),
- android `presentation: "modal"` screens are now sliding from bottom (closes #415)
> Bugfix bottom sheet

- app/permissions.tsx
- components/controls/notifications/NotificationSettings.tsx
- components/controls/notifications/SwitchControl.tsx
- hooks/useSignInOrSignUp.ts
- modules/cognito/hooks/useSignOut.ts
- modules/map/hooks/useNotificationPermission.ts
- package.json
- translations/en.json
- translations/sk.json
- utils/types.ts
- yarn.lock
- removed device from API on logout to not send notifications to logged out device,
- info panel to inform that it's forbidden to enable app notifications when they are disabled in device settings
- disabled push notification settings when the notifications are disabled in device settings
> disabled notifications and removing device when logging out

- app/(app)/tickets/filters/timeframes.tsx
- app/(app)/tickets/index.tsx
- modules/backend/constants/queryOptions.ts
- modules/backend/hooks/usePrefetchOnAppStart.tsx
- state/TicketsFiltersStoreProvider/TicketsFiltersStoreProvider.tsx
- utils/getParkingEndRange.ts
- remove `useMemo` from `now` date
- use better function names
- temporarily remove all datetimes from `queryKey` - because if some of them is not in `useMemo`, it causes infinite refetch loop
- as a potential workaround, we use `refetchOnMount: 'always'`
TODO
- investigate more why infinite refetch loop happens
> Remove useMemo from parkingEnd date in Tickets History screen, use better names

- app/(app)/(purchase-and-payment)/purchase/payment.tsx
- app/(app)/about/webview.tsx
- show spinner as an overlay above webview content
The reason is, that there is a little moment until `isLoaded` state changes, so both the spinner and the webview are displayed at the same time for this moment. Before, the spinner was above the webview, what caused a content jump just after the webview is loaded.
Now, instead of the jump, content will be under the loading overlay for a fraction of time.
Before:
After:
> #505 Show loading spinner as an overlay over content in WebView

- components/controls/date-time/DateTimePicker.tsx
dark theme removal in datepicker (closes #417)
> dark theme datepicker removal

- app/onboarding.tsx
- components/navigation/OnboardingTabBar.tsx
- components/screen-layout/InfoSlide.tsx
Images keep the square shape if possible (if there is enough vertical space) (A),
or they shrink if there is not enough space (B).
(Borders are used just on screenshots, not in code)
A
B
> #527: Fix onboarding hidden text on small screens

- components/special/StoreVersionControl.tsx
Note that ios link does not work yet, but it's a correct link. From what I found so far, it seems that it takes time to App Store to get the link to work due to search indexing.
I would like to merge these link into the code now, not wait until the ios link works.
Android needs to be tested.
> #558 Add proper update links to stores

- components/controls/date-time/TimeSelector.tsx
- utils/createPriceRequestBody.ts
The main issue was with parking tickets bought before paid period, because then the paid parking start was always rounded to minutes, but parking end was not.
The main change is `const dateNow = new Date().setSeconds(0, 0)`.
Other is just cleanup.
> #577 Fix `parkingStart` and `parkingEnd` to be sent rounded to minutes

- app/(app)/feedback/index.tsx
- components/shared/Field.tsx
- translations/en.json
- translations/sk.json
- closes #595
Note: We don't have design for helptext in figma, so we follow the pattern from Bratislava DS (helptext above the field).
> #595 Add feedback message helptext

- app/(app)/filters.tsx
- app/(app)/vehicles/index.tsx
- components/list-rows/SelectRow.tsx
- use SectionList instead of custom layout
- closes #601 
- closes bratislava/paas-mpa-private#6
- improve styles also in SectionList in map filters
> #601 Use SectionList in Vehicles screen to fix collapsed text

- modules/map/hooks/useLocation.ts
- modules/map/hooks/useLocationPermission.ts
- do not recenter after `getCurrentPositionAsync` is obtained because it caused second recenter even when user moved the map pin - instead, the new position will be used just when user presses the GPS button
- cleanup unused code
I tried to test it on physical device (iphone 15) and it seems to work. Further testing with physical device in terrain could be useful.
> #586 Fix double map recenter when GPS enabled

- app/(app)/payment-options.tsx
- app/(app)/settings/index.tsx
- app/(app)/vehicles/index.tsx
- components/parking-cards/EmailsBottomSheet.tsx
- components/tickets/TicketsHistoryBottomSheet.tsx
- fix `BottomSheet` didn't appear on three-dots button press in Vehicles screen and Ticket History screen
- closes #531 
- closes bratislava/paas-mpa-private#1
The issue is probably caused when ReducedMotion is enabled. Note that `ReducedMotion` is also enabled when battery is <10% (on ios).
Quick explanation of the problem and the fix:
With newer version of `react-native-reanimated` that included support for `ReducedMotion`, `BottomSheet` has problem to appear if `ReducedMotion` is enabled. It's supposed to be fixed in BottomSheet version 4.6.3 (latests at this time), but [people write](https://github.com/gorhom/react-native-bottom-sheet/issues/1560#issuecomment-2183549675) it's still buggy, and the upgrade to newer version should be done with proper testing, not as quick fix.
So I …
> #531 Temporary fix for BottomSheet to show also when ReducedMotion is on

- components/controls/notifications/NotificationSettings.tsx
- translations/en.json
- translations/sk.json
Temporarily show infobanner, until we implement `react-native-notifications`.
> #594 Add infobanner on android to check notifications permissions

- app/(app)/tickets/filters/timeframes.tsx
- components/map/MapLocationBottomSheet.tsx
- components/map/MapPointBottomSheet.tsx
- components/tickets/PurchaseBottomSheet.tsx
- add the same hotfix to all `BottomSheet`s (before it was added only to `BottomSheetModal`s) as in #604 
- move `key` to fragment in `timeframes` bottom sheet, because it showed error "duplicate key" 🤷
> #612 Fix BottomSHeets when Reduced Motion enabled

- app/(app)/payment-options.tsx
- app/(app)/settings/index.tsx
- app/(app)/tickets/filters/timeframes.tsx
- app/(app)/vehicles/index.tsx
- components/map/MapLocationBottomSheet.tsx
- components/map/MapPointBottomSheet.tsx
- components/parking-cards/EmailsBottomSheet.tsx
- components/screen-layout/BottomSheet/BottomSheetTopAttachment.tsx
- components/tickets/PurchaseBottomSheet.tsx
- components/tickets/TicketsHistoryBottomSheet.tsx
- package.json
- yarn.lock
- removed todo text from gothom bottom sheet library issue because it's fixed in the latest version, but now it's feature, not a hotfix to a bug 😄,
- the height state of BottomSheetTopAttachment in new version of react-native-reanimated starts to be 0 in hook useAnimatedStyle. In my opinion it's because it runs on UI thread and state on JS thread so the value differs
> #650 resolve issue with top attachment that disapears on rerender

- app.config.js
- package.json
Add missing IOS APS entitlement to app.config.js.
Originally should have been added in the update to expo v51.
> #659 Add ios aps entitlement

- app/(app)/about/index.tsx
- app/(app)/menu.tsx
- components/special/StoreVersionControl.tsx
- translations/en.json
- translations/sk.json
- utils/navigateToStore.ts
- refactor the about items to not support Link component, but router.navigate instead because some items need to not have Link there,
- add navigateToStore function that navigates to https links
- add navigateToStoreReviews function that has deeplink to stores which open reviews
> #212 Add rate app action row to about page

- components/screen-layout/StackScreenWithHeader.tsx
Placeholder removes the title typography's stretch when Icons are mounted or unmounted
> #377 add empty icons to header when there is no icon

- .eas/build/build-and-maestro-test.yml
- .maestro/add-vehicles.yaml
- .maestro/purchase.yaml
Change test according to the removal of the confirm modal for the normal type of licence plates
> #693 remove the additional click in add-vehicles test

- .maestro/login.yaml
- .maestro/prolongate.yaml
- .maestro/shorten.yaml
- app/(auth)/sign-in/index.tsx
- components/inputs/Captcha.tsx
- eas.json
- translations/en.json
- translations/sk.json
The second stage includes two tries and then the signup.
We found some of the captcha verifications fail (10 in 5 days) so we want to know whether they will fail on second try, because turnstile docs suggest to retry the captcha on errors like those.
PR includes
- add retry to captcha after one failed one,
- add error message so user knows what is happening
> #702 Captcha second stage integration

- app/(app)/(purchase-and-payment)/purchase/index.tsx
- modules/backend/constants/queryOptions.ts
- remove price object useMemo,
- move refetch query interval inside queryOptions instead of useEffect,
- remove another redundant useEffect and rename vehicle state (i couldn't help myself and did it here)
> #727 remove priceObject useMemo and cleanup useEffects

- .maestro/login.yaml
- app.config.js
- app/(auth)/sign-in/index.tsx
- components/shared/DismissKeyboard.tsx
- package.json
`TouchableWithoutFeedback` inside `DismissKeyboard` component interacted badly with `ScrollView` and prevented it in some cases, 
- add comment to `DismissKeyboard` and checked all the usage with `ScrollView` (only one was in sign-in page),
- remove `DismissKeyboard` from sign-in and add `keyboardDismissMode="on-drag"` instead,
- fixed the login test
> fix: scrollable login and test fix

- app/(app)/_layout.tsx
after going to application with deep link (to /tickets) we don't provide back button to return to index screen because router will put it as only item in stack, therefore we need to add initialRouteName to enable this in app layout
There was other option with useEffect and setting index route with each deep link (with `navigation.reset(...)`), but it's not good option.
> #769 Add initialRouteName to fix deep links
